### ISSUE TITLE
Add support for GitHub token

### ISSUE THREAD

**Issue by rvignolo** [multiversx/mx-sdk-rust-contract-builder#59]
It would be great if we could be able to send a GitHub token to the docker image such that it can fetch private repositories and perform the reproducible build with this as well. 

What do you think?

**Comment by andreibancioiu** [comment]
Hello @rvignolo,

Generally speaking, no GitHub token should be passed to the workflow.

In your private repository, do this:

```
...

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml...
```

Let us know how it goes :pray: 

Additional references:
 - https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by rvignolo** [comment]
Hi @andreibancioiu!

Sorry, let me better explain. Our actions are working properly. The issue arises when there is a dependency of one smart contract `A` with another smart contract `B`, and the smart contract `B` is hosted in a private repository. Then, we need to give credentials for the CI.

This can be solved using GitHub Deploy Keys. We are using those in conjunction with the following action:

```yml
      - name: Setup Credentials
        uses: webfactory/ssh-agent@v0.9.0
        if: inputs.has-private-dependencies
        with:
          ssh-private-key: |
            ${{ secrets.sc-1-deploy-pk }}
            ${{ secrets.sc-2-deploy-pk }}
            ${{ secrets.sc-3-deploy-pk }}
```

and it works. 

The problem is with the reproducible build. We need to give credentials to the docker instance. We are currently using `cargo vendor` to solve the problem. Any ideas?
